### ISSUE TITLE
Timer never seems to call callback

### ISSUE THREAD

**Issue by michaelwschultz** [MorsGames/WalrusTimer#1] opened 2021-09-12 21:49 UTC
Running version 2.3.4

I'm simply trying to run a function after 60 frames. Even on repeat, this function never gets called. I've placed this in a create event. Does it need to live someplace else?

```
showMessage= function() {
  show_debug_message("test timer")
}

timer(showMessage, 60, true)
```

**Comment by MorsGames** [comment] 2021-09-13 17:29
Your code seems correct to me. Do you call timer_system_update() anywhere within your code? You can put it to the Begin Step event a persistent object you create at the start of the game.

Oh, and you should also use timer_system_room_end() alongside it, at the Room End event of the same object.

**Comment by MorsGames** [comment] 2022-03-31 17:57
Well, I'll just assume that the issue is resolved and close this for now.

**Closed as completed by MorsGames** 2022-03-31 17:57 UTC
